//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/ScriptableObjects/InputSystem/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""55b7d7d1-3157-4e48-af1e-ed0e84a58c8d"",
            ""actions"": [
                {
                    ""name"": ""ShipMove"",
                    ""type"": ""PassThrough"",
                    ""id"": ""4e909484-3f46-4232-8081-cdef01141b86"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShipPrimaryShoot"",
                    ""type"": ""Button"",
                    ""id"": ""62f84ffc-ffca-45f4-ac59-b9a2f909c1d5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(pressPoint=1.401298E-45,behavior=2)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShipSecondaryShoot"",
                    ""type"": ""Button"",
                    ""id"": ""4b9386a9-0588-4fb5-9ff8-15d349d7b6f7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(pressPoint=1.401298E-45,behavior=2)"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""6dc01575-5a85-45bd-ad34-eadc4f7ba152"",
                    ""path"": ""3DVector(mode=1)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShipMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""50a7de6b-4c43-4e4e-aae1-d366191f75e1"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShipMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""e8a65631-9239-4509-8daf-04f706ba7b42"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShipMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""66cd4a78-c0b3-43d0-9b6f-1e6a10217298"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShipMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""3b99e417-c276-414f-89a5-788541178b58"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShipMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""dec53caa-d81e-4480-958e-33c6133b6b0d"",
                    ""path"": ""<Accelerometer>/acceleration"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShipMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2a774fe0-a686-4078-80fa-e2f454a162c3"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShipPrimaryShoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e2fd7a6b-973f-4a45-b778-68bc890eed15"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShipSecondaryShoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_ShipMove = m_Player.FindAction("ShipMove", throwIfNotFound: true);
        m_Player_ShipPrimaryShoot = m_Player.FindAction("ShipPrimaryShoot", throwIfNotFound: true);
        m_Player_ShipSecondaryShoot = m_Player.FindAction("ShipSecondaryShoot", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_ShipMove;
    private readonly InputAction m_Player_ShipPrimaryShoot;
    private readonly InputAction m_Player_ShipSecondaryShoot;
    public struct PlayerActions
    {
        private @InputActions m_Wrapper;
        public PlayerActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @ShipMove => m_Wrapper.m_Player_ShipMove;
        public InputAction @ShipPrimaryShoot => m_Wrapper.m_Player_ShipPrimaryShoot;
        public InputAction @ShipSecondaryShoot => m_Wrapper.m_Player_ShipSecondaryShoot;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @ShipMove.started += instance.OnShipMove;
            @ShipMove.performed += instance.OnShipMove;
            @ShipMove.canceled += instance.OnShipMove;
            @ShipPrimaryShoot.started += instance.OnShipPrimaryShoot;
            @ShipPrimaryShoot.performed += instance.OnShipPrimaryShoot;
            @ShipPrimaryShoot.canceled += instance.OnShipPrimaryShoot;
            @ShipSecondaryShoot.started += instance.OnShipSecondaryShoot;
            @ShipSecondaryShoot.performed += instance.OnShipSecondaryShoot;
            @ShipSecondaryShoot.canceled += instance.OnShipSecondaryShoot;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @ShipMove.started -= instance.OnShipMove;
            @ShipMove.performed -= instance.OnShipMove;
            @ShipMove.canceled -= instance.OnShipMove;
            @ShipPrimaryShoot.started -= instance.OnShipPrimaryShoot;
            @ShipPrimaryShoot.performed -= instance.OnShipPrimaryShoot;
            @ShipPrimaryShoot.canceled -= instance.OnShipPrimaryShoot;
            @ShipSecondaryShoot.started -= instance.OnShipSecondaryShoot;
            @ShipSecondaryShoot.performed -= instance.OnShipSecondaryShoot;
            @ShipSecondaryShoot.canceled -= instance.OnShipSecondaryShoot;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnShipMove(InputAction.CallbackContext context);
        void OnShipPrimaryShoot(InputAction.CallbackContext context);
        void OnShipSecondaryShoot(InputAction.CallbackContext context);
    }
}
